### model
model_name_or_path: ByteDance-Seed/UI-TARS-1.5-7B
image_max_pixels: 262144
trust_remote_code: true            # vision-language models need this

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64                       # renamed
lora_alpha: 16
lora_target: q_proj,v_proj          # new (or “all”)
bnb_4bit: true                      # QLoRA switch

### dataset
dataset: waveui_clicks              # must exist in data/dataset_info.json
template: sharegpt                  # chat template used by your script
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: output/ui_tars_waveui_lora
logging_steps: 20
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 32
learning_rate: 2.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.03                      # uses the val split you created
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500