### model
model_name_or_path: ByteDance-Seed/UI-TARS-1.5-7B
# quantization_bit: 4
# quantization_method: bnb # CHANGE TO BNB ON CUDA
# double_quantization: false 
trust_remote_code: true
image_max_pixels: 262144

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 16
lora_target: q_proj,v_proj

### dataset
dataset: waveui_clicks
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: output/ui_tars_waveui_lora
logging_steps: 20
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 32
learning_rate: 2.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
fp16: false
ddp_timeout: 180000000

### eval
val_size: 0.03
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500